version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: anuj_admin
      POSTGRES_PASSWORD: secure_cricket_pass
      POSTGRES_DB: cricket_connect
    ports:
      - "5432:5432"
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"